# Generated by Django 4.2.11 on 2024-06-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stud_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('gmail', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('user_username', models.CharField(max_length=100)),
            ],
        ),
    ]
